### ISSUE TITLE
Question about your Tesseract plans

### ISSUE THREAD

**Issue by maelle** [ropensci/rtika#6]
:wave: @goodmansasha!

I was browsing the tesseract tag on the blog and read "Another next step is to include an install script for the Tesseract OCR software 13. Out of the box, Tika will be enhanced by Tesseract for pdf files with document images if Tesseract is available on the system. For installation tips, see https://wiki.apache.org/tika/TikaOCR and https://github.com/tesseract-ocr/tesseract/wiki." in your blog post about `rtika`. 

What do you mean exactly? Do you know of [@jeroen's `tesseract` package](https://github.com/ropensci/tesseract), could it be used for what you had in mind?

**Comment by soshsquatch** [comment]
The early idea was to include a Tesseract installer. However, given the high level of savvy of R users, I've put that aside for now. @jeroen's tesseract package includes detailed installation instructions that people can use: 

https://github.com/ropensci/tesseract

Speaking of installation, it is probably worth upgrading tesseract occasionally. I recall reading that an upcoming version of Tesseract will have improved accuracy for messy source images that are rotated or have different size texts.

Once tesseract is installed, Tika has a simple and configuration-free routine to extract OCR'd text from many image formats and PDFs. Tika does minor preprocessing such as image rotation and conversion to TIFF.

 If that minor preprocessing is not sufficient, for now one might use Jeroen's imagemagick to do some additional custom preprocessing before hand. This might include extracting portions of an image that have the same text size and rotating it. 

An idea for rtika, that might or might not be useful to people, would be to include very basic control over Tesseract from rtika. The Tika batch processing format was in development and appears to be stabilizing. I recall it has the option to turn tesseract off for some types of MIME types. For example, you might turn it off for PDFs. There also *could* eventually be the ability to pass configuration settings from Tika to tesseract through this config file. 

Tim Allison is the authority on Tika (https://twitter.com/_tallison). If someone wanted to look into the batch config file situation and report back here, that would be useful.

**Comment by maelle** [comment]
I don't follow all the details but it'd be good to add a paragraph about `tesseract` (and `magick`) to `rtika`'s README/vignette and vice versa (i.e. a note about `rtika` in `tesseract`'s docs) indicating when to use which? I can open a specific issue for that.

**Comment by soshsquatch** [comment]
Okay, I revised the README!
